# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: PPN

dependencies:
  - python=3.11

  - pip:
    - keras
    - tensorflow
    - hickle==2.1.0
    - matplotlib
